### ISSUE TITLE
All output goes to stderr

### ISSUE THREAD

**Issue by will-in-wi** [njh/ruby-waveinfo#4]
Could a debug flag be added so that I can disable the warnings going from this gem to stderr? Our sysadmins are getting an email every night because we use this gem in a cron job.

I'll take a whack at a patch for this.

**Comment by njh** [comment]
Sorry for being so rubbish at picking this up. Totally makes sense and thank you very much for the patch.

**Comment by njh** [comment]
Version 0.0.4 now released:
https://rubygems.org/gems/waveinfo
